### ISSUE TITLE
The README got messed up when my commit got merged

### ISSUE THREAD

**Issue by chris-ortiz-sndk** [tlaplus/PlusCalCheatSheet#2]
Hi Markus,

Thanks for merging my 2 edits on the tex and pdf files. Those are the files I only changed and I did not modify the README. I now noticed that the README on this github page has red LaTeX entries. I believe the README has to be regenerated, for which I don't know how. Sorry for the inconveniences.

Best regards,
Zitro

**Comment by lemmy** [comment]
https://github.com/tlaplus/PlusCalCheatSheet/commit/b51757cba6ca07ed43f8d64fa242f4ad63742124 should take care of it.  This was not caused by your PR!  Thanks

**Comment by chris-ortiz-sndk** [comment]
Hi Markus, thanks for confirming that it is not because of my PR. The README I was talking about is not the file Readme.md in the repo but the README on this github page that if you will scroll down you will see a lot of LaTeX entries.
